version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "15432:5432"
    volumes:
      - /data/postgres:/var/lib/postgresql/data 

  postgres-test:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres2022!
      POSTGRES_DB: test
    ports:
      - '15433:5432'  

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "Postgres2022!"
    ports:
      - "15434:80"
    depends_on:
      - postgres

networks: 
  postgres-compose-network:
    driver: bridge