version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres2022!
      POSTGRES_DB: test
    ports:
      - '15432:5432'
    volumes:
      - /data/postgres:/var/lib/postgresql/data

networks: 
  postgres-compose-network:
    driver: bridge